runtime: python39
entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GOOGLE_API_KEY: "YOUR_GOOGLE_API_KEY"
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always 